/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteFilmyRouteImport } from './routes/_site.filmy'
import { Route as SiteKontoRouteImport } from './routes/_site.konto'
import { Route as SiteListaRouteImport } from './routes/_site.lista'
import { Route as SiteProgramyRouteImport } from './routes/_site.programy'
import { Route as SiteSerialeRouteImport } from './routes/_site.seriale'
import { Route as SiteSzukajRouteImport } from './routes/_site.szukaj'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminGatunkiRouteImport } from './routes/admin.gatunki'
import { Route as AdminTytulyRouteImport } from './routes/admin.tytuly'
import { Route as AdminUzytkownicyRouteImport } from './routes/admin.uzytkownicy'
import { Route as OgladajSlugRouteImport } from './routes/ogladaj.$slug'
import { Route as SiteGatunekSlugRouteImport } from './routes/_site.gatunek.$slug'
import { Route as SiteTytulSlugRouteImport } from './routes/_site.tytul.$slug'
import { Route as AdminTytulyIdRouteImport } from './routes/admin.tytuly.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFilmyRoute = SiteFilmyRouteImport.update({
  id: '/filmy',
  path: '/filmy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteKontoRoute = SiteKontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => SiteRoute,
} as any)
const SiteListaRoute = SiteListaRouteImport.update({
  id: '/lista',
  path: '/lista',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProgramyRoute = SiteProgramyRouteImport.update({
  id: '/programy',
  path: '/programy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSerialeRoute = SiteSerialeRouteImport.update({
  id: '/seriale',
  path: '/seriale',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSzukajRoute = SiteSzukajRouteImport.update({
  id: '/szukaj',
  path: '/szukaj',
  getParentRoute: () => SiteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGatunkiRoute = AdminGatunkiRouteImport.update({
  id: '/gatunki',
  path: '/gatunki',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTytulyRoute = AdminTytulyRouteImport.update({
  id: '/tytuly',
  path: '/tytuly',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUzytkownicyRoute = AdminUzytkownicyRouteImport.update({
  id: '/uzytkownicy',
  path: '/uzytkownicy',
  getParentRoute: () => AdminRoute,
} as any)
const OgladajSlugRoute = OgladajSlugRouteImport.update({
  id: '/ogladaj/$slug',
  path: '/ogladaj/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteGatunekSlugRoute = SiteGatunekSlugRouteImport.update({
  id: '/gatunek/$slug',
  path: '/gatunek/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTytulSlugRoute = SiteTytulSlugRouteImport.update({
  id: '/tytul/$slug',
  path: '/tytul/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const AdminTytulyIdRoute = AdminTytulyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTytulyRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/filmy': typeof SiteFilmyRoute
  '/konto': typeof SiteKontoRoute
  '/lista': typeof SiteListaRoute
  '/programy': typeof SiteProgramyRoute
  '/seriale': typeof SiteSerialeRoute
  '/szukaj': typeof SiteSzukajRoute
  '/admin/gatunki': typeof AdminGatunkiRoute
  '/admin/tytuly': typeof AdminTytulyRouteWithChildren
  '/admin/uzytkownicy': typeof AdminUzytkownicyRoute
  '/ogladaj/$slug': typeof OgladajSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/gatunek/$slug': typeof SiteGatunekSlugRoute
  '/tytul/$slug': typeof SiteTytulSlugRoute
  '/admin/tytuly/$id': typeof AdminTytulyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/filmy': typeof SiteFilmyRoute
  '/konto': typeof SiteKontoRoute
  '/lista': typeof SiteListaRoute
  '/programy': typeof SiteProgramyRoute
  '/seriale': typeof SiteSerialeRoute
  '/szukaj': typeof SiteSzukajRoute
  '/admin/gatunki': typeof AdminGatunkiRoute
  '/admin/tytuly': typeof AdminTytulyRouteWithChildren
  '/admin/uzytkownicy': typeof AdminUzytkownicyRoute
  '/ogladaj/$slug': typeof OgladajSlugRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/gatunek/$slug': typeof SiteGatunekSlugRoute
  '/tytul/$slug': typeof SiteTytulSlugRoute
  '/admin/tytuly/$id': typeof AdminTytulyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_site/filmy': typeof SiteFilmyRoute
  '/_site/konto': typeof SiteKontoRoute
  '/_site/lista': typeof SiteListaRoute
  '/_site/programy': typeof SiteProgramyRoute
  '/_site/seriale': typeof SiteSerialeRoute
  '/_site/szukaj': typeof SiteSzukajRoute
  '/admin/gatunki': typeof AdminGatunkiRoute
  '/admin/tytuly': typeof AdminTytulyRouteWithChildren
  '/admin/uzytkownicy': typeof AdminUzytkownicyRoute
  '/ogladaj/$slug': typeof OgladajSlugRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_site/gatunek/$slug': typeof SiteGatunekSlugRoute
  '/_site/tytul/$slug': typeof SiteTytulSlugRoute
  '/admin/tytuly/$id': typeof AdminTytulyIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/filmy'
    | '/konto'
    | '/lista'
    | '/programy'
    | '/seriale'
    | '/szukaj'
    | '/admin/gatunki'
    | '/admin/tytuly'
    | '/admin/uzytkownicy'
    | '/ogladaj/$slug'
    | '/admin/'
    | '/gatunek/$slug'
    | '/tytul/$slug'
    | '/admin/tytuly/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/filmy'
    | '/konto'
    | '/lista'
    | '/programy'
    | '/seriale'
    | '/szukaj'
    | '/admin/gatunki'
    | '/admin/tytuly'
    | '/admin/uzytkownicy'
    | '/ogladaj/$slug'
    | '/'
    | '/admin'
    | '/gatunek/$slug'
    | '/tytul/$slug'
    | '/admin/tytuly/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/login'
    | '/_site/filmy'
    | '/_site/konto'
    | '/_site/lista'
    | '/_site/programy'
    | '/_site/seriale'
    | '/_site/szukaj'
    | '/admin/gatunki'
    | '/admin/tytuly'
    | '/admin/uzytkownicy'
    | '/ogladaj/$slug'
    | '/_site/'
    | '/admin/'
    | '/_site/gatunek/$slug'
    | '/_site/tytul/$slug'
    | '/admin/tytuly/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  OgladajSlugRoute: typeof OgladajSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/filmy': {
      id: '/_site/filmy'
      path: '/filmy'
      fullPath: '/filmy'
      preLoaderRoute: typeof SiteFilmyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/konto': {
      id: '/_site/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof SiteKontoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/lista': {
      id: '/_site/lista'
      path: '/lista'
      fullPath: '/lista'
      preLoaderRoute: typeof SiteListaRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/programy': {
      id: '/_site/programy'
      path: '/programy'
      fullPath: '/programy'
      preLoaderRoute: typeof SiteProgramyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/seriale': {
      id: '/_site/seriale'
      path: '/seriale'
      fullPath: '/seriale'
      preLoaderRoute: typeof SiteSerialeRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/szukaj': {
      id: '/_site/szukaj'
      path: '/szukaj'
      fullPath: '/szukaj'
      preLoaderRoute: typeof SiteSzukajRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/gatunki': {
      id: '/admin/gatunki'
      path: '/gatunki'
      fullPath: '/admin/gatunki'
      preLoaderRoute: typeof AdminGatunkiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tytuly': {
      id: '/admin/tytuly'
      path: '/tytuly'
      fullPath: '/admin/tytuly'
      preLoaderRoute: typeof AdminTytulyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/uzytkownicy': {
      id: '/admin/uzytkownicy'
      path: '/uzytkownicy'
      fullPath: '/admin/uzytkownicy'
      preLoaderRoute: typeof AdminUzytkownicyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ogladaj/$slug': {
      id: '/ogladaj/$slug'
      path: '/ogladaj/$slug'
      fullPath: '/ogladaj/$slug'
      preLoaderRoute: typeof OgladajSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/gatunek/$slug': {
      id: '/_site/gatunek/$slug'
      path: '/gatunek/$slug'
      fullPath: '/gatunek/$slug'
      preLoaderRoute: typeof SiteGatunekSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/tytul/$slug': {
      id: '/_site/tytul/$slug'
      path: '/tytul/$slug'
      fullPath: '/tytul/$slug'
      preLoaderRoute: typeof SiteTytulSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/tytuly/$id': {
      id: '/admin/tytuly/$id'
      path: '/$id'
      fullPath: '/admin/tytuly/$id'
      preLoaderRoute: typeof AdminTytulyIdRouteImport
      parentRoute: typeof AdminTytulyRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SiteRouteChildren {
  SiteFilmyRoute: typeof SiteFilmyRoute
  SiteKontoRoute: typeof SiteKontoRoute
  SiteListaRoute: typeof SiteListaRoute
  SiteProgramyRoute: typeof SiteProgramyRoute
  SiteSerialeRoute: typeof SiteSerialeRoute
  SiteSzukajRoute: typeof SiteSzukajRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteGatunekSlugRoute: typeof SiteGatunekSlugRoute
  SiteTytulSlugRoute: typeof SiteTytulSlugRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteFilmyRoute: SiteFilmyRoute,
  SiteKontoRoute: SiteKontoRoute,
  SiteListaRoute: SiteListaRoute,
  SiteProgramyRoute: SiteProgramyRoute,
  SiteSerialeRoute: SiteSerialeRoute,
  SiteSzukajRoute: SiteSzukajRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteGatunekSlugRoute: SiteGatunekSlugRoute,
  SiteTytulSlugRoute: SiteTytulSlugRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AdminTytulyRouteChildren {
  AdminTytulyIdRoute: typeof AdminTytulyIdRoute
}

const AdminTytulyRouteChildren: AdminTytulyRouteChildren = {
  AdminTytulyIdRoute: AdminTytulyIdRoute,
}

const AdminTytulyRouteWithChildren = AdminTytulyRoute._addFileChildren(
  AdminTytulyRouteChildren,
)

interface AdminRouteChildren {
  AdminGatunkiRoute: typeof AdminGatunkiRoute
  AdminTytulyRoute: typeof AdminTytulyRouteWithChildren
  AdminUzytkownicyRoute: typeof AdminUzytkownicyRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminGatunkiRoute: AdminGatunkiRoute,
  AdminTytulyRoute: AdminTytulyRouteWithChildren,
  AdminUzytkownicyRoute: AdminUzytkownicyRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  OgladajSlugRoute: OgladajSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
